# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Norm Executable

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build NormJs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.6.0

      - name: Install dependencies
        run: npm install

      - name: Build NormJs
        run: npm run build

      - name: Upload build folder as asset
        uses: actions/upload-artifact@v2
        with:
          path: build
          name: NormJs
